server:
  port: 8080
  servlet:
    context-path: /springboot1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot1
    username: root
    password: Trandat123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "2p7zBc3MarCTlKhTx4PkPrFCVNiwJv9tPO0wR6iwZBK31mSBK23+V2CYDXqe8pJl"
